#!/bin/ksh

set -ex -o pipefail

. /lib/svc/share/smf_include.sh

# set up the users required for wicket and support.
USERS=(
    (user=wicket group=wicket gecos='Wicket User' nopasswd=1 shell='/bin/sh')
    (user=support group=support gecos='Oxide Support' homedir='/home/support'
        shell='/bin/bash' profiles=('Primary Administrator')
    )
)

for i in "${!USERS[@]}"; do
    nameref u=USERS[$i]

    # Add a new group for the user.
    getent group "${u.group}" >/dev/null 2>&1 || groupadd "${u.group}"
    # Add the user.
    getent passwd "${u.user}" >/dev/null 2>&1 || \
        useradd -m -s "${u.shell}" -g "${u.group}" -c "${u.gecos}" \
        "${u.user}"

    # Either enable passwordless login (wicket) or disable password-based logins
    # completely (support, which logs in via ssh key).
    if ((u.nopasswd)); then
        passwd -d "${u.user}"
    else
        passwd -N "${u.user}"
    fi

    # Assign or remove profiles
    if [[ -n "${u.profiles}" ]]; then
        usermod -P"$(printf '%s,' "${u.profiles[@]}")" "${u.user}"
    else
        usermod -P '' "${u.user}"
    fi

    if [[ -n "${u.homedir}" ]]; then
        mkdir -p "${u.homedir}"
        for f in .bashrc .profile; do
            cp "/root/$f" "${u.homedir}/$f"
        done
        chown -R "${u.user}" "${u.homedir}"
    fi
done

# enable ipv6 forwarding and routing
pfexec routeadm -e ipv6-forwarding -u

# not required if fdb0 route in fancyfeast
#pfexec routeadm -e ipv6-routing -u

# TODO: once lbs_dpd can accept "claim" packets, route a more general prefix
# for randomized addresses
BOUNDARY_SERVICES_PREFIX="fd00:99::"

# if on the frostypaws scrimlet
if dladm | grep ixgbe5 > /dev/null;
then
    # program in routes to fancyfeast for startup dendrite programming (nexus using OPTE)
    # next hop is enp1s0 on fancyfeast
    route add -inet6 "${BOUNDARY_SERVICES_PREFIX}"/64 fe80::21b:21ff:fec1:fb30 -ifp ixgbe5

    # program in a specific route to put geneve traffic through opte
    # next hop is ixgbe3
    route add -inet6 fd00:1122:3344:104::1/128 fe80::8261:5fff:fe11:ab31 -ifp ixgbe4
else
    # program in routes to fancyfeast for startup dendrite programming (nexus using OPTE)
    # next hop is enp4s0 on fancyfeast
    route add -inet6 "${BOUNDARY_SERVICES_PREFIX}"/64 fe80::4a22:54ff:fe40:8790 -ifp e1000g4

    # program in a specific route to put geneve traffic through opte
    # next hop is e1000g5
    route add -inet6 fd00:1122:3344:102::1/128 fe80::6a05:caff:fe15:bdec -ifp e1000g3
fi

exit $SMF_EXIT_OK

